name: Generate Version Number
on:
  push:
    branches:
      - test

jobs:
  generate_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +%Y-%m-%d)"

      - name: Count commits for today
        id: commit_count
        run: |
          today=$(date +%Y-%m-%d)
          commit_count=$(git log --since="${today}T00:00:00Z" --until="${today}T23:59:59Z" --format=oneline | wc -l)
          echo "::set-output name=commit_count::${commit_count}"

      - name: Set version number
        id: set_version
        run: |
          major_version=$(../../package.json)
          today=$(date +%Y-%m-%d)
          commit_count=${{ steps.commit_count.outputs.commit_count }}
          echo "Generated version number: V${major_version}.${today}.${commit_count}"
          echo "::set-output name=version::V${major_version}.${today}.${commit_count}"

      - name: Print version number
        run: |
          echo "Generated version number: ${{ steps.set_version.outputs.version }}"
