name: Generate Version Number
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  generate_version:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout PR branch and all PR commits'
        uses: actions/checkout@v4
        with:
            ref: "master"
            fetch-depth: 0

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +%Y-%m-%d)"

      - name: Get major version from package.json
        id: major_version
        run: echo "::set-output name=major_version::$(jq -r '.version' package.json)"
        
      - name: Count commits on master branch for the specified date
        id: commit_count
        run: |
          commit_count=$(git log --oneline --since="${today} 00:00" --until="${today} 23:59" | wc -l)
          echo "Total commits on 'master' branch for ${today}: $commit_count"
          echo "::set-output name=commit_count::$commit_count"

      - name: Set version number
        id: set_version
        run: |
          today=$(date +%Y-%m-%d)
          commit_count=${{ steps.commit_count.outputs.commit_count }}
          echo "Generated version number: ${major_version}.${today}.${commit_count}"
          echo "::set-output name=version:: ${major_version}.${today}.${commit_count}"

      - name: Print version number
        run: |
          echo "Generated version number: ${{ steps.set_version.outputs.version }}"
