name: Generate Version Number
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  generate_version:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout PR branch and all PR commits'
        uses: actions/checkout@v4
        with:
            ref: "master"
            fetch-depth: 0

      - name: Count commits on master branch for the specified date
        id: commit_count
        run: |
          date_to_check="${{ github.event.inputs.date }}"
          commit_count=$(git log --oneline --since="${date_to_check} 00:00" --until="${date_to_check} 23:59" | wc -l)
          echo "Total commits on 'master' branch for ${date_to_check}: $commit_count"
          echo "::set-output name=commit_count::$commit_count"

      - name: Set version number
        id: set_version
        run: |
          date_to_use="${{ github.event.inputs.date }}"
          commit_count=${{ steps.commit_count.outputs.commit_count }}
          echo "Generated version number: V1.0.${date_to_use}.${commit_count}"
          echo "::set-output name=version::V1.0.${date_to_use}.${commit_count}"

      - name: Print version number
        run: |
          echo "Generated version number: ${{ steps.set_version.outputs.version }}"
