name: Call Generic Workflow

on:
  push:
    branches:
      - master

permissions:
  actions: write
  contents: write
  pull-requests: write
  
jobs:
  invoke-generic-workflow:
    uses: bq-priyanshu-18/release-please-auto-merge/.github/workflows/generic.yml@main
    with:
      release_type: 'node'
    secrets: inherit  # Inherit secrets if needed

  # release-check:
  #    runs-on: ubuntu-latest  
  #    needs: invoke-generic-workflow 
  #    if: ${{ needs.invoke-generic-workflow.outputs.release_prs_created }} == 'true'
  #    steps:
  #     - name: Release Check
  #       run: |
  #        echo "Release check ::::"

  merge-pull-request:
    runs-on: ubuntu-latest
    # permissions:
    #   actions: write
    #   contents: write
    #   pull-requests: write
      
    needs: invoke-generic-workflow
    if: ${{ needs.invoke-generic-workflow.outputs.release_prs_created }} == 'true'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # - name: Extract headBranchName
      #   id: extract_branch_name
      #   run: |
      #     HEAD_BRANCH_NAME=$(echo '${{ needs.invoke-generic-workflow.outputs.release_prs }}' | jq -r '.[0].headBranchName')
      #     echo "HEAD_BRANCH_NAME=$HEAD_BRANCH_NAME" >> $GITHUB_ENV
      #     echo "steps name :: $HEAD_BRANCH_NAME"
      #     # echo "test : ${{ needs.invoke-generic-workflow.outputs.release_prs }}"
      #     # echo "release pr  : ${{ needs.invoke-generic-workflow.outputs.release_prs_created }}"

      - name: Merge Pull Request
        run: |
          PR_NUMBER=$(gh pr list --state open --head release-please--branches--master--components--backend --json number --limit 1 | jq '.[] | .number')
          if [ -n "$PR_NUMBER" ]; then
            gh pr merge $PR_NUMBER --merge --auto --delete-branch
            echo "PR #$PR_NUMBER merged and branch deleted."
          else
            echo "No PR found to merge."
          fi
        env:
          GITHUB_TOKEN: ${{ github.token }}          