name: Call Generic Workflow

on:
  push:
    branches:
      - master

jobs:
  invoke-generic-workflow:
    uses: bq-priyanshu-18/release-please-auto-merge/.github/workflows/generic.yml@main
    with:
      release_type: 'node'

  merge-pull-request:
    runs-on: ubuntu-latest
    needs: invoke-generic-workflow
    # if: needs.invoke-generic-workflow.outputs.release_prs_created == 'true'
    steps:
     - name: Debug Output
       run: |
        echo "release_prs_created: ${{ needs.invoke-generic-workflow.outputs.release_prs_created }}"

     - name: Merge Pull Request
       run: |
         PR_NUMBER=$(gh pr list --state open --head release-please--branches--main--components--backend --json number --limit 1 | jq '.[] | .number')
         if [ -n "$PR_NUMBER" ]; then
           gh pr merge $PR_NUMBER --merge --auto --delete-branch
           echo "PR #$PR_NUMBER merged and branch deleted."
         else
           echo "No PR found to merge."
         fi
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
